### ISSUE TITLE
Generate v0 LUH2 unified netcdf data files

### ISSUE THREAD

**Issue by glemieux** [glemieux/fates#26]
Generate unified 

### Tasks
- [ ] Develop file name standard
#### Historic data
- [ ] Generate `f45` historic file
- [ ] Generate `f1.9` historic file
